environment:
  global:
    PROJECT_NAME: logi-lcd
  matrix:
    # Stable channel
    - CHANNEL: stable
      TARGET: x86_64-pc-windows-gnu
      DLL_TARGET: x64
    - CHANNEL: stable
      TARGET: i686-pc-windows-gnu
      DLL_TARGET: x86
    - CHANNEL: stable
      TARGET: x86_64-pc-windows-msvc
      DLL_TARGET: x64
    - CHANNEL: stable
      TARGET: i686-pc-windows-msvc
      DLL_TARGET: x86

    # Beta channel
    - CHANNEL: beta
      TARGET: x86_64-pc-windows-gnu
      DLL_TARGET: x64
    - CHANNEL: beta
      TARGET: i686-pc-windows-gnu
      DLL_TARGET: x86
    - CHANNEL: beta
      TARGET: x86_64-pc-windows-msvc
      DLL_TARGET: x64
    - CHANNEL: beta
      TARGET: i686-pc-windows-msvc
      DLL_TARGET: x86

    # Nightly channel
    - CHANNEL: nightly
      TARGET: x86_64-pc-windows-gnu
      DLL_TARGET: x64
    - CHANNEL: nightly
      TARGET: i686-pc-windows-gnu
      DLL_TARGET: x86
    - CHANNEL: nightly
      TARGET: x86_64-pc-windows-msvc
      DLL_TARGET: x64
    - CHANNEL: nightly
      TARGET: i686-pc-windows-msvc
      DLL_TARGET: x86

matrix:
  allow_failures:
    - CHANNEL: nightly

install:
  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build: false

test_script:
  # Build, we can't really test without the actual hardware
  - cargo build --verbose
  - cargo build --verbose --example mono-blink

branches:
  only:
    - master