[package]
name = "logi-lcd"
version = "0.1.0"
authors = ["Henning Ottesen <henning@live.no>"]

[target.'cfg(windows)'.dependencies]
logi-lcd-sys = {path = "logi-lcd-sys"}
widestring = "0.2.2"

[features]
copy_to_output = ["logi-lcd-sys/copy_to_output"]
