[package]
name = "logi-lcd-sys"
version = "0.1.0"
authors = ["Henning Ottesen <henning@live.no>"]
description = "Rust FFI bindings for the Logitech LCD SDK."
links = "LogitechLcd"
build = "build.rs"

[dependencies]
winapi = "0.2.8"

[build-dependencies]
winreg = "0.4"
